development:
  adapter: postgresql
  encoding: utf8
  database: snippets_development
  pool: 5
  username: mohammed
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: mohammed
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST